platform :ios, '9.0'

target 'WeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherApp
    pod "UPCarouselFlowLayout"
    pod 'SDWebImage', '~> 5.0'

end
